python3 kevalx2.py ADBE
python3 kevalx2.py  AMZN
python3 kevalx2.py  ATVI
python3 kevalx2.py  BIDU
python3 kevalx2.py  DD
python3 kevalx2.py  EA
python3 kevalx2.py  IBKR
python3 kevalx2.py  INTC
python3 kevalx2.py  KO
python3 kevalx2.py  MKC
python3 kevalx2.py  MSFT
python3 kevalx2.py  MU
python3 kevalx2.py  NFLX
python3 kevalx2.py  NKE
python3 kevalx2.py  NVDA
python3 kevalx2.py  ORCL
python3 kevalx2.py  SBUX
python3 kevalx2.py  WMT
