all:hello.cpp
	g++ -I/usr/local/include -L/usr/local/lib hello.cpp -ltensorflow -o cpptf    

crx:main.c
	gcc -I/usr/local/include -L/usr/local/lib main.c -ltensorflow -o ctf    

one:one.cpp
	g++ -std=c++11 -I/ds/github/tensorflow/third_party/eigen3/ -I/usr/local/include -I/ds/github/tensorflow/ -L/usr/local/lib one.cpp -ltensorflow -o one    
