all:hello.cpp
	g++ -I/usr/local/include -L/usr/local/lib hello.cpp -ltensorflow -o cpptf    

crx:main.c
	gcc -I/usr/local/include -L/usr/local/lib main.c -ltensorflow -o ctf    

one:one.cpp
	g++ -I/usr/local/include -L/usr/local/lib one.cpp -ltensorflow -o one    
